import Head from 'next/head'
import Layout from '../components/Layout'

export default function Home() {
  return (
    <div>
      <Head>
        <title>120Studio - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
        <style>

        </style>

      </Head>

      <Layout>
        <header className="w3-container w3-purple w3-center titlePadding">
          <h1 className="w3-margin w3-jumbo">120 Studio</h1>
          <p className="w3-xlarge">Provide free productivity tools for you!</p>
          <a style={{ paddingLeft: "20" }} href="https://github.com/120Studio/120home">
            <button className="w3-button w3-black w3-padding-large w3-large w3-margin-top">Support</button>
          </a>
        </header>

        <div className="w3-row-padding w3-padding-64 w3-container">
          <div className="w3-content">
            <div className="w3-twothird">
              <h1><a href="./drivemark.html">Drive Bookmark</a></h1>
              <h5 className="w3-padding-32">Map your Google Drive to your bookmark. You can easily access for your drive
                files including team folder via bookmark.</h5>

              <p className="w3-text-grey">
                How many times did you switch different Google drives to find your file?
                <br />
                How many times did you repeatly search for the same file?
                <br />
                How messy your bookmark is without any organize?
              </p>
            </div>

            <div className="w3-third w3-center">
              <a href="./drivemark.html">
                <img src='./assets/bookmark-128.png' className="fa fa-anchor w3-padding-64"></img>
              </a>
            </div>
          </div>
        </div>

        <div className="w3-row-padding w3-padding-64 w3-container">
          <div className="w3-content">
            <div className="w3-twothird">
              <h1>
                <a href="./webinstagram.html">Extension for Instagram</a>
              </h1>
              <h5 className="w3-padding-32">A free chrome extension to view instagram with all <b>mobile</b> features.
                <ul>Uploading photos/videos directly from your desktop</ul>
                <ul>Download Instagram videos and photos to your desktop</ul>
                <ul>Full experience of Instagram Mobile Web look and feel in a normal Chrome tab</ul>
              </h5>

              <p className="w3-text-grey">
                Do you want to upload pictures to Instagram from your desktop?
                <br />
                Do you want to view all posts in instagram silimar on your mobile device?
              </p>
            </div>

            <div className="w3-third w3-center">
              <a href="https://chrome.google.com/webstore/detail/drive-mark/gailnkgbkabnclnnponepghblkbjgkfl">
                <img src='./assets/instagram-128.png' className="fa fa-anchor w3-padding-64"></img>
              </a>
            </div>
          </div>
        </div>
      </Layout>
    </div>
  )
}
